config/routes.rb
TrailBlazingTails::Application.routes.draw do
  resources :admin_users

  get "admin", :to => "access#index"

  get "access/logout"

  post "access/attempt_login"
  
  get "access/login"
  
  get "access/runner_index"

  resources :orders

  resources :pay_periods

  resources :runs

  resources :runners

  resources :dogs

  resources :clients

  resources :accounts

end

app/models/account.rb
class Account < ActiveRecord::Base

	attr_reader :account_number

	has_many :clients
	has_many :dogs
	has_many :runs

	after_initialize :account_number

	def account_number
		if self.id
			self.id + 10000
		end
	end

	def process_order(order)
		if order.valid?
			self.orders << order
			if order.dog.second_dog?
				self.silver_run_credits = self.silver_run_credits + order.quantity
			else
				self.gold_run_credits = self.gold_run_credits + order.quantity
			end
		end
	end

	def cancel_order(order)
		if order.dog.second_dog?
			self.silver_run_credits = self.silver_run_credits - order.quantity
		else
			self.gold_run_credits = self.gold_run_credits - order.quantity
		end
	end

end

app/models/admin.rb
class Admin < User
	
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base

	validates :email, uniqueness: true

	has_secure_password
	
end

app/models/client.rb
class Client < ActiveRecord::Base

	belongs_to :account

end

app/models/dog.rb
class Dog < ActiveRecord::Base

	belongs_to :account
	has_many :runs
end

app/models/order.rb
class Order < ActiveRecord::Base

	belongs_to :dog
	belongs_to :account

	validates :dog_id, presence: true
end

app/models/pay_period.rb
class PayPeriod < ActiveRecord::Base
	has_many :runs
end

app/models/run.rb
class Run < ActiveRecord::Base

	belongs_to :dog
	belongs_to :runner
	belongs_to :account
	belongs_to :pay_period

end

app/models/runner.rb
class Runner < User

	has_many :runs
	
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  
  before_action :confirm_logged_in, 
    :except => [:login, :attempt_login, :logout]

  def index
  	# display text and links specific to user roll
  	# AdminUser
  	# Runner
    @user = User.find(session[:user_id])
    if @user.type == "Runner"
      redirect_to(:action => 'runner_index')
    end
  end

  def runner_index
    # runner menu
    @runner = Runner.find(session[:user_id])
  end

  def login
  	# login form
  end

  def attempt_login
  	if params[:email].present? && params[:password].present?
  		found_user = User.where(:email => params[:email]).first
  		if found_user
  			authorized_user = found_user.authenticate(params[:password])
  		end
  	end
  	if authorized_user
  		# mark user as logged in
      session[:user_id] = authorized_user.id
      session[:user_type] = authorized_user.type
      flash[:notice] = 'you are now logged in'
      redirect_to(:action => 'index')
    else
      flash[:error] = "Invalid email or password"
      redirect_to(:action => 'login')
  	end
  end

  def logout
  	# mark user as logged out
    session[:user_id] = nil
    session[:user_level] = nil
  	flash[:notice] = "Logged out"
  	redirect_to(:action => "login")
  end



end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dog }
      else
        format.html { render action: 'new' }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :breed, :run_rate, :sit_rate, :age, :notes, :additional_dog, :account_id)
    end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :confirm_logged_in
  before_action :set_run, only: [:show, :edit, :update, :destroy]

  # GET /runs
  # GET /runs.json
  def index
    @runs = case session[:user_type]
    when "Runner" then Run.where(runner_id: session[:user_id])
    when "Admin" then Run.all
    end
  end

  # GET /runs/1
  # GET /runs/1.json
  def show
  end

  def runs_for_runner
    @runs = Run.where(id: session[user_id]).order('created_at DESC')
    render action: index
  end

  # GET /runs/new
  def new
    @run = Run.new
    @runner = Runner.find(session[:user_id])
  end

  # GET /runs/1/edit
  def edit
    @runner = Runner.find(Run.find(params[:id]).runner_id)
  end

  # POST /runs
  # POST /runs.json
  def create
    @run = Run.new(run_params)

    dog = Dog.find(@run.dog_id)

    if dog.additional_dog?
      @run.value = "silver"
    else
      @run.value = "gold"
    end

    respond_to do |format|
      if @run.save
        format.html { redirect_to @run, notice: 'Run was successfully created.' }
        format.json { render action: 'show', status: :created, location: @run }
      else
        format.html { render action: 'new' }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /runs/1
  # PATCH/PUT /runs/1.json
  def update
    respond_to do |format|
      if @run.update(run_params)
        format.html { redirect_to @run, notice: ' run was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runs/1
  # DELETE /runs/1.json
  def destroy
    @run.destroy
    respond_to do |format|
      format.html { redirect_to runs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_run
      @run = Run.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def run_params
      params.require(:run).permit(:dog_id, :runner_id, :run_date, :duration, :map_url, :page, :value, :account_id)
    end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pay_periods_helper.rb
module PayPeriodsHelper
end

app/helpers/runners_helper.rb
module RunnersHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/views/dogs/_form.html.erb
<%= form_for(@dog) do |f| %>
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% @dog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :run_rate %><br>
    <%= f.text_field :run_rate %>
  </div>
  <div class="field">
    <%= f.label :sit_rate %><br>
    <%= f.text_field :sit_rate %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="field">
    <%= f.label :additional_dog %><br>
    <%= f.check_box :additional_dog %>
  </div>
  <div class="field">
    <%= f.label :account_id %><br>
    <%= f.text_field :account_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<h1>Listing dogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Breed</th>
      <th>Run rate</th>
      <th>Sit rate</th>
      <th>Age</th>
      <th>Notes</th>
      <th>Additional dog</th>
      <th>Account</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.name %></td>
        <td><%= dog.breed %></td>
        <td><%= dog.run_rate %></td>
        <td><%= dog.sit_rate %></td>
        <td><%= dog.age %></td>
        <td><%= dog.notes %></td>
        <td><%= dog.additional_dog %></td>
        <td><%= dog.account %></td>
        <td><%= link_to 'Show', dog %></td>
        <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
        <td><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New dog', new_dog_path %>

app/views/dogs/new.html.erb
<h1>New dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dog.name %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @dog.breed %>
</p>

<p>
  <strong>Run rate:</strong>
  <%= @dog.run_rate %>
</p>

<p>
  <strong>Sit rate:</strong>
  <%= @dog.sit_rate %>
</p>

<p>
  <strong>Age:</strong>
  <%= @dog.age %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @dog.notes %>
</p>

<p>
  <strong>Additional dog:</strong>
  <%= @dog.additional_dog %>
</p>

<p>
  <strong>Account:</strong>
  <%= @dog.account %>
</p>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>

app/views/runs/_form.html.erb
<%= form_for(@run) do |f| %>
  <% if @run.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@run.errors.count, "error") %> prohibited this run from being saved:</h2>

      <ul>
      <% @run.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label @runner.first_name %> <%= f.label @runner.last_name %> 
  </div>  
  <div class="field">
    <%= f.label :dog_id %><br>
    <%= f.collection_select(:dog_id, Dog.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.hidden_field :runner_id, :value => @runner.id %>
  </div>
  <div class="field">
    <%= f.label :run_date %><br>
    <%= f.date_select :run_date %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :map_url %><br>
    <%= f.text_field :map_url %>
  </div>
  <div class="field">
    <%= f.label :pace %><br>
    <%= f.text_field :pace %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :account_id %><br>
    <%= f.text_field :account_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/runs/edit.html.erb
<h1>Editing run</h1>

<%= render 'form' %>

<%= link_to 'Show', @run %> |
<%= link_to 'Back', runs_path %>

app/views/runs/index.html.erb
<h1>Listing runs</h1>

<table>
  <thead>
    <tr>
      <th>Dog</th>
      <th>Runner</th>
      <th>Run date</th>
      <th>Duration</th>
      <th>Map url</th>
      <th>Pace</th>
      <th>Value</th>
      <th>Account</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @runs.each do |run| %>
      <tr>
        <td><%= run.dog.name %></td>
        <td><%= run.runner.first_name %> <%= run.runner.last_name %></td>
        <td><%= run.run_date %></td>
        <td><%= run.duration %></td>
        <td><%= run.map_url %></td>
        <td><%= run.pace %></td>
        <td><%= run.value %></td>
        <td><%= run.account %></td>
        <td><%= link_to 'Show', run %></td>
        <td><%= link_to 'Edit', edit_run_path(run) %></td>
        <td><%= link_to 'Destroy', run, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Log a run', new_run_path %> | <%= link_to 'Back to main menu', {controller: :access, action: :index} %>

app/views/runs/new.html.erb
<h1>New run</h1>

<%= render 'form' %>

<%= link_to 'Back', {:controller => :access, :action => :index} %>

app/views/runs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dog:</strong>
  <%= @run.dog.name %>
</p>

<p>
  <strong>Runner:</strong>
  <%= @run.runner.first_name %> <%= @run.runner.last_name %>
</p>

<p>
  <strong>Run date:</strong>
  <%= @run.run_date %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @run.duration %>
</p>

<p>
  <strong>Map url:</strong>
  <%= @run.map_url %>
</p>

<p>
  <strong>Pace:</strong>
  <%= @run.pace %>
</p>

<p>
  <strong>Value:</strong>
  <%= @run.value %>
</p>

<p>
  <strong>Account:</strong>
  <%= @run.account %>
</p>

<%= link_to 'Edit', edit_run_path(@run) %> |
<%= link_to 'Back', {action: "index" } %>