config/routes.rb
TrailBlazingTails::Application.routes.draw do
  resources :admin_users

  get "admin", :to => "access#index"

  get "access/logout"

  post "access/attempt_login"
  
  get "access/login"
  
  get "access/runner_index"

  resources :orders

  resources :pay_periods

  resources :runs

  resources :runners

  resources :dogs

  resources :clients

  resources :accounts

end

app/models/account.rb
class Account < ActiveRecord::Base

	attr_reader :account_number

	has_many :clients
	has_many :dogs
	has_many :runs

	after_initialize :account_number

	def account_number
		if self.id
			self.id + 10000
		end
	end

	def process_order(order)
		if order.valid?
			self.orders << order
			if order.dog.second_dog?
				self.silver_run_credits = self.silver_run_credits + order.quantity
			else
				self.gold_run_credits = self.gold_run_credits + order.quantity
			end
		end
	end

	def cancel_order(order)
		if order.dog.second_dog?
			self.silver_run_credits = self.silver_run_credits - order.quantity
		else
			self.gold_run_credits = self.gold_run_credits - order.quantity
		end
	end

end

app/models/admin.rb
class Admin < User
	
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base

	validates :email, uniqueness: true

	has_secure_password
	
end

app/models/client.rb
class Client < ActiveRecord::Base

	belongs_to :account

end

app/models/dog.rb
class Dog < ActiveRecord::Base

	belongs_to :account
	has_many :runs
end

app/models/order.rb
class Order < ActiveRecord::Base

	belongs_to :dog
	belongs_to :account

	validates :dog_id, presence: true
end

app/models/pay_period.rb
class PayPeriod < ActiveRecord::Base
	has_many :runs
end

app/models/run.rb
class Run < ActiveRecord::Base

	belongs_to :dog
	belongs_to :runner
	belongs_to :account
	belongs_to :pay_period

end

app/models/runner.rb
class Runner < User

	has_many :runs
	
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  before_action :set_admin_user, only: [:show, :edit, :update, :destroy]

  # GET /admin_users
  # GET /admin_users.json
  def index
    @admin_users = AdminUser.all
  end

  # GET /admin_users/1
  # GET /admin_users/1.json
  def show
  end

  # GET /admin_users/new
  def new
    @admin_user = AdminUser.new
  end

  # GET /admin_users/1/edit
  def edit
  end

  # POST /admin_users
  # POST /admin_users.json
  def create
    @admin_user = AdminUser.new(admin_user_params)

    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to @admin_user, notice: 'Admin user was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admin_user }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin_users/1
  # PATCH/PUT /admin_users/1.json
  def update
    respond_to do |format|
      if @admin_user.update(admin_user_params)
        format.html { redirect_to @admin_user, notice: ' admin user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_users/1
  # DELETE /admin_users/1.json
  def destroy
    @admin_user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = AdminUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_user_params
      params.require(:admin_user).permit(:fisrt_name, :last_name, :email, :password_digest)
    end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dog }
      else
        format.html { render action: 'new' }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :breed, :run_rate, :sit_rate, :age, :notes, :additional_dog, :account_id)
    end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :confirm_logged_in
  before_action :set_run, only: [:show, :edit, :update, :destroy]

  # GET /runs
  # GET /runs.json
  def index
    @runs = case session[:user_type]
    when "Runner" then Run.where(runner_id: session[:user_id])
    when "Admin" then Run.all
    end
  end

  # GET /runs/1
  # GET /runs/1.json
  def show
  end

  def runs_for_runner
    @runs = Run.where(id: session[user_id]).order('created_at DESC')
    render action: index
  end

  # GET /runs/new
  def new
    @run = Run.new
    @runner = Runner.find(session[:user_id])
  end

  # GET /runs/1/edit
  def edit
    @runner = Runner.find(Run.find(params[:id]).runner_id)
  end

  # POST /runs
  # POST /runs.json
  def create
    @run = Run.new(run_params)

    dog = Dog.find(@run.dog_id)

    if dog.additional_dog?
      @run.value = "silver"
    else
      @run.value = "gold"
    end

    respond_to do |format|
      if @run.save
        format.html { redirect_to @run, notice: 'Run was successfully created.' }
        format.json { render action: 'show', status: :created, location: @run }
      else
        format.html { render action: 'new' }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /runs/1
  # PATCH/PUT /runs/1.json
  def update
    respond_to do |format|
      if @run.update(run_params)
        format.html { redirect_to @run, notice: ' run was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runs/1
  # DELETE /runs/1.json
  def destroy
    @run.destroy
    respond_to do |format|
      format.html { redirect_to runs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_run
      @run = Run.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def run_params
      params.require(:run).permit(:dog_id, :runner_id, :run_date, :duration, :map_url, :page, :value, :account_id)
    end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pay_periods_helper.rb
module PayPeriodsHelper
end

app/helpers/runners_helper.rb
module RunnersHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/views/admin_users/_form.html.erb
<%= form_for(@admin_user) do |f| %>
  <% if @admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
      <% @admin_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fisrt_name %><br>
    <%= f.text_field :fisrt_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password_digest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin_users/edit.html.erb
<h1>Editing admin_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_user %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin_users/index.html.erb
<h1>Listing admin_users</h1>

<table>
  <thead>
    <tr>
      <th>Fisrt name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_users.each do |admin_user| %>
      <tr>
        <td><%= admin_user.fisrt_name %></td>
        <td><%= admin_user.last_name %></td>
        <td><%= admin_user.email %></td>
        <td><%= admin_user.password_digest %></td>
        <td><%= link_to 'Show', admin_user %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(admin_user) %></td>
        <td><%= link_to 'Destroy', admin_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fake admin user', new_admin_user_path %>

app/views/admin_users/new.html.erb
<h1>New admin_user</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fisrt name:</strong>
  <%= @admin_user.fisrt_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @admin_user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin_user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @admin_user.password_digest %>
</p>

<%= link_to 'Edit', edit_admin_user_path(@admin_user) %> |
<%= link_to 'Back', admin_users_path %>